#include "degisken.h"

degisken::degisken()
{
    //fatura
    ftrSutunSil=0;
    ftrSutunDegistir=1;
    ftrSutunKayitNo=2;
    ftrSutunTarih=3;
    ftrSutunIsim=4;
    ftrSutunMatrah=5;
    ftrSutunKdvOrani=6;
    ftrSutunKdvTutar=7;
    ftrSutunTutar=8;
    ftrSutunAciklama=9;
    ftrSutunTur=10;
    ftrSutunHesap=11;
    ftrSutunKayit=12;
    ftrSutunDegisim=13;
    ftrSutunKilit=14;
    //////////////////
    //maas
    msSutunSil=0;
    msSutunDegistir=1;
    msSutunTarih=2;
    msSutunCalisan=3;
    msSutunMaas=4;
    msSutunAy=5;
    msSutunTur=6;
    msSutunHesap=7;
    msSutunKayit=8;
    msSutunDegisim=9;
    msSutunKilit=10;
    //////////////////
    //hesap
    hspSutunSil=0;
    hspSutunDegistir=1;
    hspSutunIsim=2;
    hspSutunBaslangicMeblagi=3;
    hspSutunGuncelMeblag=4;
    hspSutunTur=5;
    hspSutunKayit=6;
    hspSutunDegisim=7;
    hspSutunKilit=8;
    //////////////////
}
